[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ollama_query"
version = "0.1.1"
dependencies = [
  "requests"
]

[tool.setuptools.packages.find]
where = ["src"]
